name: PATRICKGRIDTEST
favicon: null
layout_spectrum: 0.5678356499411166
typography_spectrum: 0.8944999063387513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7293082803953439
  lightness: 0.41371657978743315
  saturation: 0.4198594761546701
  rhythmicContrast: 0.9296453795395792
purpose: []
